services:
  - type: web
    name: dontdie
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///dontdie.db
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      # For production, you should set these as secrets in the Render dashboard
      # - key: MAIL_USERNAME
      #   sync: false
      # - key: MAIL_PASSWORD
      #   sync: false 